"""Add User model

Revision ID: e432d390f94c
Revises: dcbead3492b8
Create Date: 2025-05-19 00:06:59.758353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e432d390f94c'
down_revision = 'dcbead3492b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.drop_constraint('activity_logs_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('database_entries', schema=None) as batch_op:
        batch_op.drop_constraint('database_entries_added_by_fkey', type_='foreignkey')
        batch_op.drop_column('added_by')

    with op.batch_alter_table('threat_checks', schema=None) as batch_op:
        batch_op.drop_constraint('threat_checks_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=False)
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
        batch_op.drop_column('is_active')
        batch_op.drop_column('email')

    with op.batch_alter_table('threat_checks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('threat_checks_user_id_fkey', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('database_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('added_by', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('database_entries_added_by_fkey', 'users', ['added_by'], ['id'])

    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('activity_logs_user_id_fkey', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
